### ISSUE TITLE
"memcpy" was not declared in this scope

### ISSUE THREAD

**Issue by GriffenJBS** [eendeego/node-openvg-canvas#1]
[2/3] cxx: src/util.cc -&gt; build/Release/src/util_1.o
../src/util.cc: In function "v8::Handle&lt;v8::Value&gt; fillArray(v8::Handle&lt;v8::Value&gt;, void*, size_t)":
../src/util.cc:47:16: error: "memcpy" was not declared in this scope

I'm getting this error, and it seems fixed by adding "#include &lt;string.h&gt;" after v8.h

**Comment by eendeego** [comment]
What node version are you using ? I'm developing with 0.8.8/0.8.9.

**Comment by GriffenJBS** [comment]
I'm using v0.8.6-pre, but that error comes from g++ running "node-waf build"

**Comment by eendeego** [comment]
I can't test this on 0.8.6. Can you confirm it that it's working now ?
Thanks!

**Comment by GriffenJBS** [comment]
I just checked, and this problem seems fixed.
