### ISSUE TITLE
KinectJS

### ISSUE THREAD

**Issue by raneri** [eendeego/node-openvg-canvas#11]
Hello,

I'm trying to use KinectJS over node-openvg-canvas to develop a canvas slideshow with some effects. Anyway it doesn't work because it expects the presence of the "document" and "window" elements. Since the canvas is running without the browser runtime, it crashes. Is there some workaround, or we have to use only "vanilla" canvas commands?

Thanks in advance!!!

**Comment by eendeego** [comment]
Hi,

For now, node-openvg-canvas doesn't provide any shims to simulate window or document (besides the requestAnimationFrame).

I don't know how much KinectJS is dependant on document and windows, but if it has a limited interaction it may be possible to shim it easily.

**Comment by raneri** [comment]
Ok, I'll ask to KinectJS guys to check if they have some advice... thank you so much for the quick reply!
