### ISSUE TITLE
API call returned invalid object

### ISSUE THREAD

**Issue by sander** [eendeego/node-openvg-canvas#12]
I just installed node.js 0.10.5 and the current git version of node-openvg-canvas. When running the swissClock.js example, a crash occurs with this error message:

```
#
# Fatal error in , line 0
# API call returned invalid object
#

Trace/breakpoint trap
```

and this backtrace:

https://gist.github.com/sander/5574315

Any idea what could be going on?

**Comment by sander** [comment]
I also tried node.js 0.8.19 (with a new ‘npm install’ in the node-openvg-canvas directory), but then the example script just gave a segmentation fault.

**Comment by eendeego** [comment]
There are some issues with node 0.10, but 0.8 should work. Are you using the node-canvas script ?

**Comment by sander** [comment]
I haven’t done anything with node-canvas, but just ran:

```
export PATH=$PWD/bin:$PATH
~/node.8/bin/node examples/swissClock.js
```

from the node-openvg-canvas directory.

**Comment by sander** [comment]
It works, thanks! I had to run:

```
export PATH=$HOME/node.8/bin:$PWD/bin:$PATH
chmod +x examples/swissClock.js
examples/swissClock.js
```

**Comment by eendeego** [comment]
Starting on 1.1.6, openvg-canvas runs on node 0.10.x (tested with 0.10.13).
