### ISSUE TITLE
compile error with node 10.8

### ISSUE THREAD

**Issue by 6Beaufort** [eendeego/node-openvg-canvas#14]
Hi Luis,

I've tried to install with a rather fresh node 10.8 on my PI. 
Here is the error caused by a missing include file:

npm http 200 https://registry.npmjs.org/uglify-js/-/uglify-js-1.1.1.tgz
make: Entering directory `/home/pi/src/node-openvg-canvas/node_modules/openvg/build'
  CXX(target) Release/obj.target/init-egl/src/init-egl.o
../src/init-egl.cc:1:21: fatal error: EGL/egl.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/init-egl/src/init-egl.o] Error 1
make: Leaving directory`/home/pi/src/node-openvg-canvas/node_modules/openvg/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.10.24
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/src/node-openvg-canvas/node_modules/openvg
gyp ERR! node -v v0.10.8
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

pi@raspbmc:~/src/node-openvg-canvas$ node --version
v0.10.8

**Comment by eendeego** [comment]
It looks like you don't have a raspbian distribution.

The missing egl.h file should be at `/opt/vc/include/EGL/`

Can you check if you have it ?

You may have to install `libraspberrypi-dev`

**Comment by 6Beaufort** [comment]
yes, that was it, thank you!

I am using raspbmc and dev environment is incomplete here by default.
solved it by cloning https://github.com/raspberrypi/firmware to tmp dir and moving include, lib and sbin to /opt/vc.

BTW, I am going to deliver pages to a browser and would need canvas.toDataURL() for that. It says "not implemented yet". DO you have plans to implement that soon? Otherwise I would have to use node-canvas.

**Comment by eendeego** [comment]
You don't need `canvas.toDataURL` to extract image data, you can use `canvas.toBuffer` (that curiously enough mimics the node-canvas api). You can see a running example of this at https://github.com/luismreis/node-openvg-canvas/blob/master/examples/imageSource.js#L38

Also, this code is not prepared for concurrent access (as expected from a node http server), so, most probably, node-canvas is a much better option for this - it was built with that exact purpose, AFAIK.

**Comment by 6Beaufort** [comment]
Thank you for both infos Luis!
