### ISSUE TITLE
cannot install...

### ISSUE THREAD

**Issue by ffloress** [eendeego/node-openvg-canvas#28]
Hello, I cannot npm install...
I am installed node 11.4 s suggested. but I see many many errors like this:

../src/openvg.cc:1855:12: error: 'NanScope' was not declared in this scope
../src/openvg.cc:1863:35: error: 'args' was not declared in this scope
../src/openvg.cc:1874:22: error: 'NanReturnUndefined' was not declared in this scope
../src/openvg.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE openvg::ext::DropShadowKHR(Nan::NAN_METHOD_ARGS_TYPE

I see there is not openvg.cc on the /src source, should I install something there?

more on the error log:

openvg.target.mk:93: recipe for target 'Release/obj.target/openvg/src/openvg.o' failed
make: **\* [Release/obj.target/openvg/src/openvg.o] Error 1
make: Leaving directory '/mnt/streaming/jardimsonoro/node-openvg-canvas/node_modules/openvg/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:103:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.18.0-trunk-rpi
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/external/node-openvg-canvas/node_modules/openvg
gyp ERR! node -v v0.11.4
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by eendeego** [comment]
Sorry. Don't use 0.11.<any minor minor release>. For now, only 0.10 is properly supported.
